language: python
python:
  - '3.5'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="mysite.settings"

services:
  - postgresql

script:
  - python ./manage.py test

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE=mysite.settings.travis

